name: GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: wolverian-dawn
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --verbose --print-build-logs
      - run: find result/
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
